### ISSUE TITLE
Ability to ignore SSL errors

### ISSUE THREAD

**Issue by coolacid** [polarityio/elasticsearch#3]
We use Lets Encrypt certs with Elasticsearch. Polarity is requiring a full chain cert for due to intermediary cert. Unfortunately, the full chain certs provided by LetsEncrypt include the DH Parameters in the cert chain which Elasticsearch balks at (I'll be checking that against later versions and opening a ticket with them later) 

For now, I'm ignoring the SSL errors inside this integration by adding the following to the `requestOptions`:

```
rejectUnauthorized: false,
```

It would be super helpful to have advanced configuration tabs and include some more advanced admin only configs including ignoring SSL errors.

**Comment by sarus** [comment]
Supported now right from the Polarity Integration settings UI!
